---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-monitoring
  template:
    metadata:
      labels:
        app: serverless-monitoring
    spec:
      containers:
      - name: serverless-monitoring
        image: fernandapereira/serverless-monitoring
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/serverless-monitoring/usermodule.py"
          subPath: pyfile
        env:
        - name: REDIS_HOST
          value: "192.168.121.66"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
